#!/usr/bin/env python3
"""
CPS3 sprite compositor engine — shared tile parsing, palette loading, and compositing.

This module is the reusable core imported by both extract_sprites.py (stage/char CLI)
and extract_stage.py (background chip animations). It contains no CLI or script logic.
"""

import csv as csv_mod
import json
import os
import struct
from PIL import Image

from sprite_common import (
    read_afs, read_afs_file, lz_ext_p6_fx, DTL, unswizzle,
    decode_color_abgr1555, decode_palette_banks, _clut_reorder_bank,
    STAGE_PAL_AFS, STAGE_TILE_AFS,
    TileChip, COLORS_PER_BANK, PALETTE_BANK_BYTES, TOTAL_BANKS, CHAR_PAL_ROWS,
)

# Optional NumPy for accelerated compositing
try:
    import numpy as np
    _HAS_NUMPY = True
except ImportError:
    _HAS_NUMPY = False


# ══════════════════════════════════════════════════════════════════════════════
# CPS3 Palette Constants
# ══════════════════════════════════════════════════════════════════════════════

SPRITE_PAL_BASE = 300
COMMON_PAL_AFS = 9
COMMON_PAL_SLOT = 32
STAGE_PAL_SLOT = 300

# Note: CPS3 CLUT reorder is now handled by _clut_reorder_bank in sprite_common.
# Applied at palette load time (decode_palette_banks, _load_pal_row).


# Directory containing runtime ColorRAM dump files.
COLORRAM_DUMP_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data")

# Path to colcd_map.csv (generated by runtime logger in aboutspr.c)
COLCD_MAP_CSV = os.path.join(COLORRAM_DUMP_DIR, "colcd_map.csv")


# ══════════════════════════════════════════════════════════════════════════════
# Palette Loading
# ══════════════════════════════════════════════════════════════════════════════


def load_engine_palette_map():
    """Load engine-derived CG-to-colcd map from cg_palette_map.json."""
    map_path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                            "cg_palette_map.json")
    if not os.path.exists(map_path):
        return {}
    with open(map_path, 'r') as f:
        raw = json.load(f)
    return {int(k): v for k, v in raw.items()}


def afs_entry_to_stage(apfn):
    """Map an AFS entry number to a stage index, or None."""
    _stage_afs = _build_stage_afs_entries()
    if apfn not in _stage_afs:
        return None
    for stage_idx in range(22):
        pal = STAGE_PAL_AFS[stage_idx]
        tile = STAGE_TILE_AFS[stage_idx]
        lo, hi = min(pal, tile), max(pal, tile)
        if lo <= apfn <= hi:
            return stage_idx
    return None


def _build_stage_afs_entries():
    """Compute the set of AFS entries that belong to actual stages."""
    entries = set()
    for si in range(22):
        entries.add(STAGE_PAL_AFS[si])
        entries.add(STAGE_TILE_AFS[si])
        lo = min(STAGE_PAL_AFS[si], STAGE_TILE_AFS[si])
        hi = max(STAGE_PAL_AFS[si], STAGE_TILE_AFS[si])
        for e in range(lo, hi + 1):
            entries.add(e)
    return entries


def get_rendering_mode(group_idx, stage_sprite_groups):
    """Mode 33 for stage backgrounds, Mode 18 for everything else."""
    return 33 if group_idx in stage_sprite_groups else 18


def load_colorram_dump(stage_idx, dump_dir=None):
    """Load runtime ColorRAM dump (65536 bytes: 512 banks × 64 colors × 2 bytes).

    Colors are in post-palConvSrcToRam format (R and B swapped from source).
    Returns list of 512 banks or None.
    """
    if dump_dir is None:
        dump_dir = COLORRAM_DUMP_DIR
    dump_path = os.path.join(dump_dir,
                             f"stage_{stage_idx:02d}_colorram.bin")
    if not os.path.exists(dump_path):
        return None
    with open(dump_path, "rb") as f:
        cram = f.read()
    if len(cram) != 65536:
        return None

    banks = []
    for bank in range(TOTAL_BANKS):
        colors = [(0, 0, 0, 0)] * COLORS_PER_BANK
        for i in range(COLORS_PER_BANK):
            off = bank * PALETTE_BANK_BYTES + i * 2
            val = struct.unpack_from("<H", cram, off)[0]
            # ColorRAM dump is post-palConvSrcToRam: R and B swapped
            b5 = val & 0x1F
            g5 = (val >> 5) & 0x1F
            r5 = (val >> 10) & 0x1F
            r = (r5 * 255 + 15) // 31
            g = (g5 * 255 + 15) // 31
            b = (b5 * 255 + 15) // 31
            if r == 255 and b == 255 and (g == 0 or g == 49):
                colors[i] = (0, 0, 0, 0)
            elif i == 0 and val == 0:
                colors[i] = (0, 0, 0, 0)
            else:
                colors[i] = (r, g, b, 255)
        banks.append(colors)
    return banks


def load_consensus_colorram_dump():
    """Load all available ColorRAM dumps and build a consensus by modal frequency.
    Filters out noise/corruption from active gameplay sparks and hit effects."""
    from collections import Counter
    all_dumps = []
    for i in range(20):
        d = load_colorram_dump(i)
        if d is not None:
            all_dumps.append(d)
            
    if not all_dumps:
        return None

    consensus = [[(0, 0, 0, 0)] * COLORS_PER_BANK for _ in range(TOTAL_BANKS)]
    
    for bank_idx in range(TOTAL_BANKS):
        for color_idx in range(COLORS_PER_BANK):
            colors = []
            for dump in all_dumps:
                c = dump[bank_idx][color_idx]
                if c[3] != 0: # Check alpha or just check > 0
                    colors.append(c)
            if colors:
                consensus[bank_idx][color_idx] = Counter(colors).most_common(1)[0][0]
    return consensus


def build_stage_colorram(afs_path, entries, stage_pal_afs, apply_clut=False):
    """Build merged ColorRAM[512] from common + stage palette.

    Common palette (AFS 9):   480 banks → slots 32..511
    Stage palette:             68 banks → slots 300..367 (overwrites)
    """
    colorram = [[(0, 0, 0, 0)] * COLORS_PER_BANK for _ in range(TOTAL_BANKS)]

    if COMMON_PAL_AFS < len(entries):
        common_data = read_afs_file(afs_path, entries[COMMON_PAL_AFS])
        for i, bank in enumerate(decode_palette_banks(common_data, apply_clut=apply_clut)):
            slot = COMMON_PAL_SLOT + i
            if slot < TOTAL_BANKS:
                colorram[slot] = bank

    if stage_pal_afs is not None and stage_pal_afs < len(entries):
        stage_data = read_afs_file(afs_path, entries[stage_pal_afs])
        for i, bank in enumerate(decode_palette_banks(stage_data, apply_clut=apply_clut)):
            slot = STAGE_PAL_SLOT + i
            if slot < TOTAL_BANKS:
                colorram[slot] = bank

    return colorram


def _load_pal_row(pal_data, row_idx, total_rows):
    """Load one 64-color palette row using shared decode_color_abgr1555."""
    bank = [(0, 0, 0, 0)] * COLORS_PER_BANK
    if row_idx >= total_rows:
        return bank
    for i in range(COLORS_PER_BANK):
        off = row_idx * PALETTE_BANK_BYTES + i * 2
        if off + 2 > len(pal_data):
            break
        val = struct.unpack_from("<H", pal_data, off)[0]
        bank[i] = decode_color_abgr1555(val, i)
    return bank


def build_char_colorram(afs_path, entries, pal_data, pal_idx):
    """Build merged 512-bank ColorRAM from character + common palettes.

    Character palette layout (COL struct from color3rd.c):
      28 rows of 64 colors (u16 each), total 3584 bytes.
      Rows 0-15:  costume color variants (pal_idx selects body)
      Rows 16-21: 6 fixed sub-palettes (effects, projectiles, etc.)
      Rows 22-25: extended palettes (super effects, etc.)

    Engine mapping (init_trans_color_ram type=1, non-Gill path):
      Bank base+0     = row pal_idx (body)
      Bank base+1..6  = rows 16-21 (sub-palettes)
      Bank base+8     = body (mirrored)
      Bank base+9..14 = rows 16-21 (mirrored)
      where base = id * 16 (P1=0, P2=16)

      Banks 502-505 (P1) / 506-509 (P2) = rows 22-25 (extended)
      Banks 32-511 = Common palette (AFS 9)

    We replicate at BOTH P1 and P2 offsets so runtime colcd from
    either player resolves correctly.
    """
    colorram = [[(0, 0, 0, 0)] * COLORS_PER_BANK for _ in range(TOTAL_BANKS)]
    total_rows = len(pal_data) // PALETTE_BANK_BYTES

    # Common palette into banks 32..511
    if len(entries) > COMMON_PAL_AFS:
        common_data = read_afs_file(afs_path, entries[COMMON_PAL_AFS])
        for i, bank in enumerate(decode_palette_banks(common_data, apply_clut=True)):
            if COMMON_PAL_SLOT + i < TOTAL_BANKS:
                colorram[COMMON_PAL_SLOT + i] = bank

    # Replicate character palettes at both P1 (base=0) and P2 (base=16)
    body = _load_pal_row(pal_data, pal_idx, total_rows)
    sub_pals = []
    for sub in range(7):  # rows 16-22: 7 sub-palettes (effects, projectiles, etc.)
        row = 16 + sub
        sub_pals.append(_load_pal_row(pal_data, row, total_rows) if row < total_rows
                        else [(0, 0, 0, 0)] * COLORS_PER_BANK)

    for base in (0, 16):  # P1 and P2 banks
        colorram[base] = body
        colorram[base + 8] = body  # mirrored
        for sub in range(7):
            colorram[base + 1 + sub] = sub_pals[sub]
            colorram[base + 9 + sub] = sub_pals[sub]  # mirrored

    # Extended palettes at both P1 (502-505) and P2 (506-509)
    for sub in range(4):
        row = 22 + sub
        if row < total_rows:
            ext_pal = _load_pal_row(pal_data, row, total_rows)
            colorram[502 + sub] = ext_pal
            colorram[506 + sub] = ext_pal

    return colorram


def load_character_palette(afs_path, entries, char_id, pal_banks,
                           char_pal_afs, costume=0, bank_offset=0):
    """Load a character's palette into pal_banks.

    Body (row costume) → bank_offset+0, sub-pals (rows 16-21) → bank_offset+1..6,
    extended (rows 22-25) → banks 502-505 (engine init_trans_color_ram layout).
    Used by --per-character mode to inject character palettes into stage ColorRAM.
    """
    afs_idx = char_pal_afs.get(char_id)
    if afs_idx is None or afs_idx >= len(entries):
        return

    col_data = read_afs_file(afs_path, entries[afs_idx])
    if len(col_data) < CHAR_PAL_ROWS * COLORS_PER_BANK * 2:
        return

    total_rows = len(col_data) // PALETTE_BANK_BYTES

    pal_banks[bank_offset + 0] = _load_pal_row(col_data, costume, total_rows)
    for i in range(6):
        pal_banks[bank_offset + 1 + i] = _load_pal_row(col_data, 16 + i, total_rows)
    # Extended palettes: rows 22-25 → banks 502-505 (engine init_trans_color_ram)
    for i in range(4):
        if 502 + i < len(pal_banks):
            pal_banks[502 + i] = _load_pal_row(col_data, 22 + i, total_rows)


def load_colcd_map(csv_path=None):
    """Load runtime colcd mapping from CSV → {(stage, cg_number): (colcd, mode)}.

    Returns (colcd, mode) tuples so the extractor can apply mode-specific
    normalization (Mode 17 uses exchange_current_colcd → %8, others use raw).
    """
    path = csv_path or COLCD_MAP_CSV
    if not os.path.exists(path):
        return {}
    mapping = {}
    with open(path) as f:
        for row in csv_mod.DictReader(f):
            key = (int(row["stage"]), int(row["cg_number"]))
            mode = int(row["mode"]) if "mode" in row else 0
            mapping[key] = (int(row["colcd"]), mode)
    return mapping


# ══════════════════════════════════════════════════════════════════════════════
# Tile Parsing
# ══════════════════════════════════════════════════════════════════════════════


def _parse_tiles(data, to_tex, frame_idx):
    """Parse chip tiles for a single frame. Returns list of TileChip or None."""
    if len(data) < 4:
        return None
    num_frames = struct.unpack_from("<I", data, 0)[0] // 4
    if frame_idx >= num_frames:
        return None

    foff = struct.unpack_from("<I", data, frame_idx * 4)[0]
    if foff + 2 > len(data):
        return None
    cnt = struct.unpack_from("<H", data, foff)[0]
    if cnt == 0:
        return None

    tiles = []
    eoff = foff + 2
    for _ in range(cnt):
        if eoff + 8 > len(data):
            break
        dx, dy = struct.unpack_from("<hh", data, eoff)
        attr, code = struct.unpack_from("<HH", data, eoff + 4)
        eoff += 8

        tpos = to_tex + code * 4
        if tpos + 4 > len(data):
            continue
        toff = struct.unpack_from("<I", data, tpos)[0]
        aoff = to_tex + toff
        if aoff >= len(data):
            continue

        wh = data[aoff]
        wm = (wh & 3) + 1
        td = wm * 8
        ts = (wm * wm) << 6
        dw = (wh & 0xE0) >> 2
        dh = (wh & 0x1C) * 2
        if dw == 0 or dh == 0:
            continue

        raw = lz_ext_p6_fx(data[aoff + 1:], ts)
        px = unswizzle(raw, td)
        tiles.append(TileChip(dx, dy, attr, code, td, dw, dh, px))

    return tiles if tiles else None


# ══════════════════════════════════════════════════════════════════════════════
# Position Computation
# ══════════════════════════════════════════════════════════════════════════════


def _compute_positions(tiles):
    """Compute draw positions from tile deltas, handling x-flip."""
    all_xflip = all((t.attr & 0x8000) != 0 for t in tiles)
    cx = cy = 0
    pts = []
    for t in tiles:
        if all_xflip:
            cx += t.dx
        else:
            cx -= t.dx
        cy -= t.dy
        if all_xflip:
            draw_x = cx - (t.dw if (t.attr & 0x8000) else 0)
            draw_y = cy + (t.dh if (t.attr & 0x4000) else 0)
        else:
            draw_x = cx
            draw_y = cy
        pts.append((draw_x, draw_y))
    return pts, all_xflip


# ══════════════════════════════════════════════════════════════════════════════
# Compositing Engine (NumPy + Python fallback)
# ══════════════════════════════════════════════════════════════════════════════


def _composite_numpy(tiles, pts, all_xflip, palette_fn, sw, sh, mnx, mny):
    """NumPy-accelerated tile compositing. Returns PIL Image or None."""
    buf = np.zeros((sh, sw, 4), dtype=np.uint8)

    for i, t in enumerate(tiles):
        tx = pts[i][0] - mnx
        ty = pts[i][1] - mny
        flip_x = (t.attr & 0x8000) != 0 and not all_xflip
        flip_y = (t.attr & 0x4000) != 0 and not all_xflip
        pal = palette_fn(t.attr, i)

        # Build palette as numpy array
        pal_arr = np.array(pal, dtype=np.uint8)

        # Create coordinate grids
        yo_arr = np.arange(t.dh)
        xo_arr = np.arange(t.dw)
        yy, xx = np.meshgrid(yo_arr, xo_arr, indexing='ij')

        # Apply flip
        rx = (t.dw - 1 - xx) if flip_x else xx
        ry = (t.dh - 1 - yy) if flip_y else yy

        # Scale coordinates to tile space
        if t.dw <= t.td:
            sx = rx
        else:
            sx = np.minimum(rx * t.td // t.dw, t.td - 1)
        if t.dh <= t.td:
            sy = ry
        else:
            sy = np.minimum(ry * t.td // t.dh, t.td - 1)

        # Read pixel indices from pdata
        pdata_arr = np.frombuffer(t.px, dtype=np.uint8).reshape(-1)
        src_idx = sy * t.td + sx
        # Clip to valid range
        src_idx = np.clip(src_idx, 0, len(pdata_arr) - 1)
        vals = pdata_arr[src_idx]

        # Compute destination coordinates
        ddx = tx + xx
        ddy = ty + yy

        # Build mask: non-zero pixel, in bounds, valid palette index
        mask = (vals > 0) & (ddx >= 0) & (ddx < sw) & (ddy >= 0) & (ddy < sh)
        mask &= (vals < len(pal_arr))

        # Write pixels
        valid_vals = vals[mask]
        valid_ddx = ddx[mask]
        valid_ddy = ddy[mask]
        buf[valid_ddy, valid_ddx] = pal_arr[valid_vals]

        # Handle out-of-palette pixels (grey)
        oob_mask = (vals > 0) & (vals >= len(pal_arr)) & \
                   (ddx >= 0) & (ddx < sw) & (ddy >= 0) & (ddy < sh)
        if np.any(oob_mask):
            buf[ddy[oob_mask], ddx[oob_mask]] = [128, 128, 128, 255]

    return Image.fromarray(buf, 'RGBA')


def _composite_python(tiles, pts, all_xflip, palette_fn, sw, sh, mnx, mny):
    """Pure-Python fallback tile compositing. Returns PIL Image or None."""
    img = Image.new("RGBA", (sw, sh), (0, 0, 0, 0))
    pxi = img.load()
    for i, t in enumerate(tiles):
        tx = pts[i][0] - mnx
        ty = pts[i][1] - mny
        flip_x = (t.attr & 0x8000) != 0 and not all_xflip
        flip_y = (t.attr & 0x4000) != 0 and not all_xflip
        pal = palette_fn(t.attr, i)

        for yo in range(t.dh):
            for xo in range(t.dw):
                rx = (t.dw - 1 - xo) if flip_x else xo
                ry = (t.dh - 1 - yo) if flip_y else yo
                sx = rx if t.dw <= t.td else min(rx * t.td // t.dw, t.td - 1)
                sy = ry if t.dh <= t.td else min(ry * t.td // t.dh, t.td - 1)
                v = t.px[sy * t.td + sx]
                if v == 0:
                    continue
                ddx = tx + xo
                ddy = ty + yo
                if 0 <= ddx < sw and 0 <= ddy < sh:
                    if v < len(pal):
                        pxi[ddx, ddy] = pal[v]
                    else:
                        pxi[ddx, ddy] = (128, 128, 128, 255)
    return img


def _composite(tiles, pts, all_xflip, palette_fn):
    """Composite tiles into a PIL Image using palette_fn(attr, tile_idx) → palette."""
    all_x1 = [pts[i][0] + tiles[i].dw for i in range(len(tiles))]
    all_y1 = [pts[i][1] + tiles[i].dh for i in range(len(tiles))]
    mnx = min(p[0] for p in pts)
    mny = min(p[1] for p in pts)
    mxx = max(all_x1)
    mxy = max(all_y1)
    sw = mxx - mnx
    sh = mxy - mny
    if sw <= 0 or sh <= 0:
        return None

    if _HAS_NUMPY:
        return _composite_numpy(tiles, pts, all_xflip, palette_fn, sw, sh, mnx, mny)
    return _composite_python(tiles, pts, all_xflip, palette_fn, sw, sh, mnx, mny)


# ══════════════════════════════════════════════════════════════════════════════
# Frame Extraction (public API)
# ══════════════════════════════════════════════════════════════════════════════


def extract_stage_frame(data, to_tex, frame_idx, pal_banks, colcd_base=None,
                        rendering_mode=18, skip_empty=True):
    """Extract a single stage/effect sprite frame.

    Palette dispatch:
      Mode 18 CP3: tile_pal = (attr & 0x1FF) + colcd_base
      Mode 33:     tile_pal = colcd_base + (attr & 0xF)
    """
    tiles = _parse_tiles(data, to_tex, frame_idx)
    if not tiles:
        return None

    if skip_empty and all(all(b == 0 for b in t.px) for t in tiles):
        return None

    pts, all_xflip = _compute_positions(tiles)
    base = colcd_base if colcd_base is not None else SPRITE_PAL_BASE

    def palette_fn(attr, tile_idx):
        if rendering_mode == 33:
            # Engine mlt_obj_disp: palo = colcd & 0xF, then palo + (attr & 0xE00F)
            # Offline tool: colcd_base is already shifted to 300+, don't mask with 0xF
            idx = base + (attr & 0xF)
        else:
            # Mode 18 CP3 natively uses 0x1FF. Reverting from 0xF to fix UI palette offsets.
            idx = (attr & 0x1FF) + base
        idx = idx % TOTAL_BANKS
        return pal_banks[idx] if idx < len(pal_banks) else pal_banks[0]

    return _composite(tiles, pts, all_xflip, palette_fn)


def extract_char_frame(data, to_tex, frame_idx, colorram, base_cg=0,
                       engine_pal_map=None, colcd_map=None):
    """Extract a single character animation frame.

    Palette dispatch depends on the rendering mode the engine used:
      Mode 17 (mlt_obj_trans): ALL tiles use same palo bank
      Mode 18 (mlt_obj_trans_cp3): palt = (attr & 0x1FF) + palo

    Per-CG colcd resolution (runtime CSV preferred — it carries mode info):
      1. Runtime colcd_map.csv (stage-agnostic: any stage match, has mode)
      2. Engine cg_palette_map.json (static, assumes Mode 17)
      3. Default: 0 (body palette, Mode 17)
    """
    tiles = _parse_tiles(data, to_tex, frame_idx)
    if not tiles:
        return None

    pts, all_xflip = _compute_positions(tiles)

    if engine_pal_map is None:
        engine_pal_map = {}
    if colcd_map is None:
        colcd_map = {}

    cg = base_cg + frame_idx

    # Resolve colcd: prefer runtime CSV (has mode), then engine map, else auto-detect
    colcd_base = None
    colcd_mode = 17  # default assumes Mode 17

    # 1. Runtime CSV — authoritative for MODE detection.
    #    For Mode 17, colcd is just player_id*8 (runtime artifact) — always use 0.
    #    For Mode 18, colcd encodes which palette bank the effect uses.
    for key, val in colcd_map.items():
        if key[1] == cg:
            csv_colcd, colcd_mode = val
            colcd_base = csv_colcd if colcd_mode == 18 else 0
            break

    # 2. Static engine map (cg_palette_map.json) — no mode info, assume 17
    if colcd_base is None:
        json_val = engine_pal_map.get(cg)
        if json_val is not None:
            colcd_base = json_val
            colcd_mode = 17

    # 3. Auto-detect from tile data: if any tile has attr & 0x1FF > 0,
    #    it's a Mode 18 CG (per-tile palette offsets).  Body CGs (Mode 17)
    #    always have attr & 0x1FF == 0.
    #    For Mode 18, infer colcd base from nearest CSV Mode 18 neighbor.
    if colcd_base is None:
        has_pal_attr = any((t.attr & 0x1FF) != 0 for t in tiles)
        if has_pal_attr:
            colcd_mode = 18
            # Find nearest CG in CSV with mode=18, within same character range
            best_dist = float('inf')
            colcd_base = 0  # fallback
            max_search_dist = 2000  # chars span ~1000-2000 CGs
            for key, val in colcd_map.items():
                csv_colcd, csv_mode = val
                if csv_mode == 18:
                    dist = abs(key[1] - cg)
                    if dist < best_dist and dist <= max_search_dist:
                        best_dist = dist
                        colcd_base = csv_colcd
        else:
            colcd_base = 0
            colcd_mode = 17

    def palette_fn(attr, tile_idx):
        if colcd_mode == 18:
            # Mode 18 (mlt_obj_trans_cp3): Natively uses 0x1FF for palette offsets.
            idx = (attr & 0x1FF) + colcd_base
        else:
            # Mode 17 (mlt_obj_trans): ALL tiles use same palo bank
            idx = colcd_base
        idx = idx % TOTAL_BANKS
        if idx >= len(colorram):
            idx = 0
        return colorram[idx]

    return _composite(tiles, pts, all_xflip, palette_fn)
