android.useAndroidX=true
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.builtInKotlin=true
# Suppress excludeLibraryComponentsFromConstraints performance warning
android.generateSyncIssueWhenLibraryConstraintsAreEnabled=false
android.javaCompile.suppressSourceTargetDeprecationWarning=true
