#ifndef AI_PASSIVE_CHECK_H
#define AI_PASSIVE_CHECK_H

#include "structs.h"
#include "types.h"

extern void (*const Passive_jmp_tbl[21])();
extern s32 (*const Passive_AS_tbl[20])();
extern s32 (*const Passive_A_tbl[20])();
extern s32 (*const Passive_BS_tbl[20])();
extern s32 (*const Passive_B_tbl[20])();
extern s32 (*const Passive_CS_tbl[20])();
extern s32 (*const Passive_C_tbl[20])();
extern s32 (*const Passive_DS_tbl[20])();
extern s32 (*const Passive_D_tbl[20])();

extern s8 PASSIVE_X;

s32 Ck_Passive_Term(PlayerEntity* wk);
void KEN_vs(PlayerEntity* wk);
void HUGO_vs(PlayerEntity* wk);
void GILL_vs(PlayerEntity* wk);
s32 Check_Special_Technique(PlayerEntity* wk, State* em, s16 VS_Technique, u8 Kind_of_Tech, u8 SP_Tech_ID, s16 Option,
                            s16 Option2);
s32 Check_Attack_Direction(PlayerEntity* wk, State* em);
s32 Check_VS_Jump(PlayerEntity* wk, PlayerEntity* em, s16 Height);
s32 Check_Rolling(PlayerEntity* wk, State* em);
s32 Check_Personal_Action(PlayerEntity* wk, State* em);
s32 Check_Specific_Term(PlayerEntity* wk, State* em, s16 VS_Technique, u8 Status_00, u8 Status_01, u8 Status_02);
s32 Check_Dash(PlayerEntity* wk, State* em, s16 VS_Technique);
s32 Check_Limited_Attack(PlayerEntity* wk, State* em, s16 VS_Technique, u8 PL_Status, s8 Status_00, s16 Limit_Number);
s32 Check_Limited_Jump_Attack(PlayerEntity* wk, State* em, u8 PL_Status, s8 Status_00);
s32 Check_Stand(PlayerEntity* wk, State* em, s16 VS_Technique);
s32 Setup_Next_Stand_Timer(PlayerEntity* wk);
s32 Check_VS_Squat(PlayerEntity* wk, State* em, s16 VS_Technique, u8 Status_00, u8 Status_01);
s32 Setup_Next_Squat_Timer(PlayerEntity* wk);
s32 Check_Thrown(PlayerEntity* wk, State* em);
s32 Check_Catch(PlayerEntity* wk, State* em, s16 VS_Technique);
s32 Check_Lie(PlayerEntity* wk);
s32 Check_Faint(PlayerEntity* wk, PlayerEntity* enemy, s16 VS_Technique);
s32 Check_Blow_Off(PlayerEntity* wk, State* em, s16 VS_Technique);
s32 Check_After_Attack(PlayerEntity* wk, State* em, s16 VS_Technique);
s32 Check_F_Cross_Chop(PlayerEntity* wk, State* em, s16 VS_Technique);
s32 VS_GILL_AS(PlayerEntity* wk);
s32 VS_ALEX_AS(PlayerEntity* wk);
s32 VS_RYU_AS(PlayerEntity* wk);
s32 VS_RYU_AS(PlayerEntity* wk);
s32 VS_YUN_AS(PlayerEntity* wk);
s32 VS_DUDLEY_AS(PlayerEntity* wk);
s32 VS_NECRO_AS(PlayerEntity* wk);
s32 VS_HUGO_AS(PlayerEntity* wk);
s32 VS_IBUKI_AS(PlayerEntity* wk);
s32 VS_ELENA_AS(PlayerEntity* wk);
s32 VS_ORO_AS(PlayerEntity* wk);
s32 VS_KEN_AS(PlayerEntity* wk);
s32 VS_SEAN_AS(PlayerEntity* wk);
s32 VS_URIEN_AS(PlayerEntity* wk);
s32 VS_GOUKI_AS(PlayerEntity* wk);
s32 VS_CHUN_LI_AS(PlayerEntity* wk);
s32 VS_MAKOTO_AS(PlayerEntity* wk);
s32 VS_Q_AS(PlayerEntity* wk);
s32 VS_NO12_AS(PlayerEntity* wk);
s32 VS_REMY_AS(PlayerEntity* wk);
s32 VS_GILL_A(PlayerEntity* wk);
s32 VS_ALEX_A(PlayerEntity* wk);
s32 VS_RYU_A(PlayerEntity* wk);
s32 VS_YUN_A(PlayerEntity* wk);
s32 VS_DUDLEY_A(PlayerEntity* wk);
s32 VS_NECRO_A(PlayerEntity* wk);
s32 VS_HUGO_A(PlayerEntity* wk);
s32 VS_IBUKI_A(PlayerEntity* wk);
s32 VS_ELENA_A(PlayerEntity* wk);
s32 VS_ORO_A(PlayerEntity* wk);
s32 VS_KEN_A(PlayerEntity* wk);
s32 VS_SEAN_A(PlayerEntity* wk);
s32 VS_URIEN_A(PlayerEntity* wk);
s32 VS_GOUKI_A(PlayerEntity* wk);
s32 VS_CHUN_LI_A(PlayerEntity* wk);
s32 VS_MAKOTO_A(PlayerEntity* wk);
s32 VS_Q_A(PlayerEntity* wk);
s32 VS_NO12_A(PlayerEntity* wk);
s32 VS_REMY_A(PlayerEntity* wk);
s32 VS_GILL_BS(PlayerEntity* wk);
s32 VS_ALEX_BS(PlayerEntity* wk);
s32 VS_RYU_BS(PlayerEntity* wk);
s32 VS_YUN_BS(PlayerEntity* wk);
s32 VS_DUDLEY_BS(PlayerEntity* wk);
s32 VS_NECRO_BS(PlayerEntity* wk);
s32 VS_HUGO_BS(PlayerEntity* wk);
s32 VS_IBUKI_BS(PlayerEntity* wk);
s32 VS_ELENA_BS(PlayerEntity* wk);
s32 VS_ORO_BS(PlayerEntity* wk);
s32 VS_KEN_BS(PlayerEntity* wk);
s32 VS_SEAN_BS(PlayerEntity* wk);
s32 VS_URIEN_BS(PlayerEntity* wk);
s32 VS_GOUKI_BS(PlayerEntity* wk);
s32 VS_CHUN_LI_BS(PlayerEntity* wk);
s32 VS_MAKOTO_BS(PlayerEntity* wk);
s32 VS_Q_BS(PlayerEntity* wk);
s32 VS_NO12_BS(PlayerEntity* wk);
s32 VS_REMY_BS(PlayerEntity* wk);
s32 VS_GILL_B(PlayerEntity* wk);
s32 VS_ALEX_B(PlayerEntity* wk);
s32 VS_RYU_B(PlayerEntity* wk);
s32 VS_YUN_B(PlayerEntity* wk);
s32 VS_DUDLEY_B(PlayerEntity* wk);
s32 VS_NECRO_B(PlayerEntity* wk);
s32 VS_HUGO_B(PlayerEntity* wk);
s32 VS_IBUKI_B(PlayerEntity* wk);
s32 VS_ELENA_B(PlayerEntity* wk);
s32 VS_ORO_B(PlayerEntity* wk);
s32 VS_KEN_B(PlayerEntity* wk);
s32 VS_SEAN_B(PlayerEntity* wk);
s32 VS_URIEN_B(PlayerEntity* wk);
s32 VS_GOUKI_B(PlayerEntity* wk);
s32 VS_CHUN_LI_B(PlayerEntity* wk);
s32 VS_MAKOTO_B(PlayerEntity* wk);
s32 VS_Q_B(PlayerEntity* wk);
s32 VS_NO12_B(PlayerEntity* wk);
s32 VS_REMY_B(PlayerEntity* wk);
s32 VS_GILL_CS(PlayerEntity* wk);
s32 VS_ALEX_CS(PlayerEntity* wk);
s32 VS_RYU_CS(PlayerEntity* wk);
s32 VS_YUN_CS(PlayerEntity* wk);
s32 VS_DUDLEY_CS(PlayerEntity* wk);
s32 VS_NECRO_CS(PlayerEntity* wk);
s32 VS_HUGO_CS(PlayerEntity* wk);
s32 VS_IBUKI_CS(PlayerEntity* wk);
s32 VS_ELENA_CS(PlayerEntity* wk);
s32 VS_ORO_CS(PlayerEntity* wk);
s32 VS_KEN_CS(PlayerEntity* wk);
s32 VS_SEAN_CS(PlayerEntity* wk);
s32 VS_URIEN_CS(PlayerEntity* wk);
s32 VS_GOUKI_CS(PlayerEntity* wk);
s32 VS_CHUN_LI_CS(PlayerEntity* wk);
s32 VS_MAKOTO_CS(PlayerEntity* wk);
s32 VS_Q_CS(PlayerEntity* wk);
s32 VS_NO12_CS(PlayerEntity* wk);
s32 VS_REMY_CS(PlayerEntity* wk);
s32 VS_GILL_C(PlayerEntity* wk);
s32 VS_ALEX_C(PlayerEntity* wk);
s32 VS_RYU_C(PlayerEntity* wk);
s32 VS_YUN_C(PlayerEntity* wk);
s32 VS_DUDLEY_C(PlayerEntity* wk);
s32 VS_NECRO_C(PlayerEntity* wk);
s32 VS_HUGO_C(PlayerEntity* wk);
s32 VS_IBUKI_C(PlayerEntity* wk);
s32 VS_ELENA_C(PlayerEntity* wk);
s32 VS_ORO_C(PlayerEntity* wk);
s32 VS_KEN_C(PlayerEntity* wk);
s32 VS_SEAN_C(PlayerEntity* wk);
s32 VS_URIEN_C(PlayerEntity* wk);
s32 VS_GOUKI_C(PlayerEntity* wk);
s32 VS_CHUN_LI_C(PlayerEntity* wk);
s32 VS_MAKOTO_C(PlayerEntity* wk);
s32 VS_Q_C(PlayerEntity* wk);
s32 VS_NO12_C(PlayerEntity* wk);
s32 VS_REMY_C(PlayerEntity* wk);
s32 VS_GILL_DS(PlayerEntity* wk);
s32 VS_ALEX_DS(PlayerEntity* wk);
s32 VS_RYU_DS(PlayerEntity* wk);
s32 VS_YUN_DS(PlayerEntity* wk);
s32 VS_DUDLEY_DS(PlayerEntity* wk);
s32 VS_NECRO_DS(PlayerEntity* wk);
s32 VS_IBUKI_DS(PlayerEntity* wk);
s32 VS_HUGO_DS(PlayerEntity* wk);
s32 VS_ELENA_DS(PlayerEntity* wk);
s32 VS_ORO_DS(PlayerEntity* wk);
s32 VS_KEN_DS(PlayerEntity* wk);
s32 VS_SEAN_DS(PlayerEntity* wk);
s32 VS_URIEN_DS(PlayerEntity* wk);
s32 VS_GOUKI_DS(PlayerEntity* wk);
s32 VS_CHUN_LI_DS(PlayerEntity* wk);
s32 VS_MAKOTO_DS(PlayerEntity* wk);
s32 VS_Q_DS(PlayerEntity* wk);
s32 VS_NO12_DS(PlayerEntity* wk);
s32 VS_REMY_DS(PlayerEntity* wk);
s32 VS_GILL_D(PlayerEntity* wk);
s32 VS_ALEX_D(PlayerEntity* wk);
s32 VS_RYU_D(PlayerEntity* wk);
s32 VS_YUN_D(PlayerEntity* wk);
s32 VS_DUDLEY_D(PlayerEntity* wk);
s32 VS_NECRO_D(PlayerEntity* wk);
s32 VS_HUGO_D(PlayerEntity* wk);
s32 VS_IBUKI_D(PlayerEntity* wk);
s32 VS_ELENA_D(PlayerEntity* wk);
s32 VS_ORO_D(PlayerEntity* wk);
s32 VS_KEN_D(PlayerEntity* wk);
s32 VS_SEAN_D(PlayerEntity* wk);
s32 VS_URIEN_D(PlayerEntity* wk);
s32 VS_GOUKI_D(PlayerEntity* wk);
s32 VS_CHUN_LI_D(PlayerEntity* wk);
s32 VS_MAKOTO_D(PlayerEntity* wk);
s32 VS_Q_D(PlayerEntity* wk);
s32 VS_NO12_D(PlayerEntity* wk);
s32 VS_REMY_D(PlayerEntity* wk);

#endif
