struct V2F {
    float2 texcoord : TEXCOORD0;
    float4 color : COLOR0;
};

struct F2FB {
    float4 color : COLOR0;
};

F2FB main(V2F IN, 
            uniform sampler2D texture : TEXUNIT0,
            uniform sampler2D palette : TEXUNIT1,
            uniform float is_palettized,
            uniform float2 tex_dimensions)
{
    F2FB OUT;
    OUT.color = IN.color;
    float4 tex0 = tex2D(texture, IN.texcoord);
    float4 final_color = tex0 * IN.color;
    
    if (is_palettized < -0.5f) {
        final_color = IN.color;
    } else if (is_palettized > 1.5f) {
        float byte_v = floor(tex0.a * 255.0 + 0.5);
        float pixel_x = floor(IN.texcoord.x * tex_dimensions.x);
        float is_odd = fmod(pixel_x, 2.0); // 0.0 for even, 1.0 for odd
        float final_nibble = lerp(fmod(byte_v, 16.0), floor(byte_v / 16.0), is_odd);
        final_color = tex2D(palette, float2((final_nibble + 0.5) / 256.0, 0.5)) * IN.color;
    } else if (is_palettized > 0.5f) {
        float byte_v = floor(tex0.a * 255.0 + 0.5);
        final_color = tex2D(palette, float2((byte_v + 0.5) / 256.0, 0.5)) * IN.color;
    }

    OUT.color = final_color;
    return OUT;
}
